#!/usr/bin/env python3
"""Materialize rustinel-rules packs into Rustinel-compatible artifacts.

For each pack manifest this produces, under dist/:
  - dist/<pack-id>/                 flat materialized pack folder == what the
       pack.yml                     Rustinel engine loads directly:
       rules/sigma/<file>.yml         -> scanner.sigma_rules_path
       rules/yara/<file>.yar          -> scanner.yara_rules_path
       rules/ioc/hashes.txt           -> [ioc].hashes_path
       rules/ioc/ips.txt              -> [ioc].ips_path
       rules/ioc/domains.txt          -> [ioc].domains_path
       rules/ioc/paths_regex.txt      -> [ioc].paths_regex_path
  - dist/<pack-id>-<version>.zip    zipped pack (one folder = one pack = one zip)
  - dist/index.json                 catalog of all packs + checksums + engine paths

Pack contract: one folder = one pack = one zipped Rustinel rules folder. Point
Rustinel's config at the four/five paths above (see `engine` in index.json) and
it loads with no extra glue.

Run: uv run python tools/build_packs.py [--version X.Y.Z]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import zipfile
from datetime import UTC, datetime
from pathlib import Path

import yaml

import lib

DEFAULT_VERSION = "0.2.0"

# Per-type IOC output: type -> (filename, human title, format note).
IOC_FILES = {
    "hashes": ("hashes.txt", "Hashes", "Supports MD5, SHA1, and SHA256."),
    "ips": ("ips.txt", "IPs", "Supports single IPs and CIDR ranges."),
    "domains": ("domains.txt", "Domains", 'Prefix with "." or "*." to match subdomains.'),
    "paths_regex": ("paths_regex.txt", "Path Regex", "Regex is case-insensitive."),
}


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def write_ioc_files(ioc_dir: Path, accumulated: dict) -> dict:
    """Write the four flat IOC files (always, even when empty) in the engine's
    `VALUE;COMMENT` format. Returns per-type counts."""
    ioc_dir.mkdir(parents=True, exist_ok=True)
    counts = {}
    for ioc_type in lib.IOC_TYPES:
        filename, title, note = IOC_FILES[ioc_type]
        entries = accumulated.get(ioc_type, [])
        counts[ioc_type] = len(entries)
        lines = [
            f"# IOC Type: {title}",
            "# Format: VALUE;COMMENT",
            f"# Note: {note}",
            "# Generated by rustinel-rules build — do not edit by hand.",
        ]
        for value, comment in entries:
            lines.append(f"{value};{comment}" if comment else value)
        (ioc_dir / filename).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return counts


def materialize_pack(pack: dict, by_id, artifact_index, version: str) -> dict:
    pack_id = pack["id"]
    out_dir = lib.DIST_DIR / pack_id
    if out_dir.exists():
        shutil.rmtree(out_dir)
    (out_dir / "rules" / "sigma").mkdir(parents=True, exist_ok=True)
    (out_dir / "rules" / "yara").mkdir(parents=True, exist_ok=True)

    resolved_ids = lib.resolve_pack_rules(pack, by_id)
    copied = []
    ioc_acc = {t: [] for t in lib.IOC_TYPES}

    for artifact_id in resolved_ids:
        art = artifact_index.get(artifact_id)
        if art is None:
            raise SystemExit(
                f"[build] pack '{pack_id}' references unknown artifact '{artifact_id}'"
            )

        if art.kind in ("sigma", "yara"):
            dest = out_dir / "rules" / art.kind / art.path.name
            shutil.copy2(art.path, dest)
            copied.append({"id": artifact_id, "kind": art.kind, "file": art.path.name})
        elif art.kind == "ioc":
            count = 0
            for ioc_type, entries in art.indicators.items():
                for value, comment in entries:
                    # Prefix the set id so provenance survives into engine alerts.
                    full = f"[{art.id}] {comment}" if comment else f"[{art.id}]"
                    ioc_acc[ioc_type].append((value, full))
                    count += 1
            copied.append({"id": artifact_id, "kind": "ioc", "indicators": count})

    ioc_counts = write_ioc_files(out_dir / "rules" / "ioc", ioc_acc)

    # Write a clean manifest (drop internal __path__) plus build metadata.
    manifest = {k: v for k, v in pack.items() if not k.startswith("__")}
    manifest["version"] = version
    manifest["built_at"] = datetime.now(UTC).isoformat()
    manifest["resolved_rule_count"] = sum(1 for c in copied if c["kind"] in ("sigma", "yara"))
    manifest["resolved_ioc_count"] = sum(ioc_counts.values())
    (out_dir / "pack.yml").write_text(
        yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True), encoding="utf-8"
    )

    # Zip it: dist/<pack-id>-<version>.zip
    zip_path = lib.DIST_DIR / f"{pack_id}-{version}.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in sorted(out_dir.rglob("*")):
            if file.is_file():
                zf.write(file, file.relative_to(out_dir))

    return {
        "id": pack_id,
        "name": manifest.get("name"),
        "os": manifest.get("os"),
        "level": manifest.get("level"),
        "version": version,
        "default": manifest.get("default", False),
        "requires_rustinel": manifest.get("requires_rustinel"),
        "pack_schema_version": manifest.get("pack_schema_version"),
        "status": manifest.get("status"),
        "expected_false_positive_level": manifest.get("expected_false_positive_level"),
        "attack_coverage": manifest.get("attack_coverage", []),
        "telemetry_requirements": manifest.get("telemetry_requirements", []),
        "rule_count": manifest["resolved_rule_count"],
        "ioc_count": manifest["resolved_ioc_count"],
        "rules": copied,
        "artifact": zip_path.name,
        "sha256": sha256_file(zip_path),
        # Drop-in paths for Rustinel config.toml (relative to dist/).
        "engine": {
            "sigma_rules_path": f"{pack_id}/rules/sigma",
            "yara_rules_path": f"{pack_id}/rules/yara",
            "hashes_path": f"{pack_id}/rules/ioc/hashes.txt",
            "ips_path": f"{pack_id}/rules/ioc/ips.txt",
            "domains_path": f"{pack_id}/rules/ioc/domains.txt",
            "paths_regex_path": f"{pack_id}/rules/ioc/paths_regex.txt",
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build rustinel-rules pack artifacts.")
    parser.add_argument(
        "--version", default=DEFAULT_VERSION, help="Release version (default %(default)s)"
    )
    args = parser.parse_args()

    if lib.DIST_DIR.exists():
        shutil.rmtree(lib.DIST_DIR)
    lib.DIST_DIR.mkdir(parents=True, exist_ok=True)

    packs = lib.load_packs()
    by_id = {p["id"]: p for p in packs if "id" in p}
    artifact_index = {a.id: a for a in lib.load_all_artifacts() if a.id}

    catalog = []
    for pack in packs:
        entry = materialize_pack(pack, by_id, artifact_index, args.version)
        catalog.append(entry)
        print(
            f"[build] {entry['id']}: {entry['rule_count']} rules + "
            f"{entry['ioc_count']} iocs -> {entry['artifact']}"
        )

    index = {
        "schema": "rustinel-rules/index@1",
        "generated_at": datetime.now(UTC).isoformat(),
        "release_version": args.version,
        "packs": catalog,
    }
    index_path = lib.DIST_DIR / "index.json"
    index_path.write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")
    print(f"[build] wrote {index_path.relative_to(lib.REPO_ROOT)} ({len(catalog)} packs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
